apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: openpi-data-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 50Gi
    storageClassName: csi-rbd-sc